// Auth Constants
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";

// Todo Constants
export const FETCH_TODO_REQUEST = "FETCH_TODO_REQUEST";
export const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS";
export const FETCH_TODO_FAILED = "FETCH_TODO_FAILED";

export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAILED = "ADD_TODO_FAILED";

export const MARK_TODO_REQUEST = "MARK_TODO_REQUEST";
export const MARK_TODO_SUCCESS = "MARK_TODO_SUCCESS";
export const MARK_TODO_FAILED = "MARK_TODO_FAILED";

export const EDIT_TODO_REQUEST = "EDIT_TODO_REQUEST";
export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS";
export const EDIT_TODO_FAILED = "EDIT_TODO_FAILED";

export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAILED = "DELETE_TODO_FAILED";

// User Constants
export const USER_EDIT_REQUEST = "USER_EDIT_REQUEST";
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
export const USER_EDIT_FAILED = "USER_EDIT_FAILED";

//Category Constants
export const ADD_CATGORY_REQUEST = "ADD_CATGORY_REQUEST";
export const ADD_CATGORY_SUCCESS = "ADD_CATGORY_SUCCESS";
export const ADD_CATGORY_FAILED = "ADD_CATGORY_FAILED";

export const EDIT_CATGORY_REQUEST = "EDIT_CATGORY_REQUEST";
export const EDIT_CATGORY_SUCCESS = "EDIT_CATGORY_SUCCESS";
export const EDIT_CATGORY_FAILED = "EDIT_CATGORY_FAILED";

export const DELETE_CATGORY_REQUEST = "DELETE_CATGORY_REQUEST";
export const DELETE_CATGORY_SUCCESS = "DELETE_CATGORY_SUCCESS";
export const DELETE_CATGORY_FAILED = "DELETE_CATGORY_FAILED";

export const FETCH_CATGORY_REQUEST = "FETCH_CATGORY_REQUEST";
export const FETCH_CATGORY_SUCCESS = "FETCH_CATGORY_SUCCESS";
export const FETCH_CATGORY_FAILED = "FETCH_CATGORY_FAILED";
